<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Trader;

class CopytradingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $traders = [
            [
                'name' => 'Alex Johnson',
                'photo' => 'traders/alex-johnson.jpg',
                'rating' => 5,
                'followers' => 1250,
                'equity' => 87.5,
                'total_profit' => 125000.00,
                'status' => 'active',
                'description' => 'Professional forex trader with 8+ years experience. Specializes in EUR/USD and GBP/USD pairs.',
                'bio' => 'Professional forex trader with institutional macro discipline and an emphasis on preserving capital through event-driven positioning.',
                'win_rate' => 87,
                'total_trades' => 2340,
                'price' => 500.00,
                'tag' => 'PRO',
                'type' => 'main',
                'verification_status' => 'verified',
                'strategy_type' => 'Macro FX',
                'risk_level' => 'medium',
                'trading_style' => 'Swing',
                'preferred_instruments' => 'EUR/USD, GBP/USD, XAU/USD',
                'markets_traded' => 'Forex, Metals',
                'monthly_roi' => 9.40,
                'yearly_roi' => 78.60,
                'max_drawdown' => 8.90,
                'aum' => 875000,
                'consistency_score' => 86,
                'volatility_score' => 34,
                'confidence_score' => 91,
                'capital_preservation_score' => 88,
                'recommended_investor_profile' => 'Balanced Growth',
                'minimum_allocation' => 500.00,
                'maximum_allocation' => 15000.00,
                'max_allocation_percent' => 32.00,
                'management_fee_percent' => 1.20,
                'performance_fee_percent' => 12.50,
                'is_featured' => true,
            ],
            [
                'name' => 'Sarah Chen',
                'photo' => 'traders/sarah-chen.jpg',
                'rating' => 5,
                'followers' => 890,
                'equity' => 82.3,
                'total_profit' => 98500.00,
                'status' => 'active',
                'description' => 'Crypto and forex expert. Known for conservative risk management and consistent profits.',
                'bio' => 'Cross-market trader focused on disciplined crypto momentum and defensive FX overlays.',
                'win_rate' => 82,
                'total_trades' => 1890,
                'price' => 300.00,
                'tag' => 'EXPERT',
                'type' => 'main',
                'verification_status' => 'verified',
                'strategy_type' => 'Crypto Momentum',
                'risk_level' => 'medium',
                'trading_style' => 'Systematic',
                'preferred_instruments' => 'BTC/USD, ETH/USD, EUR/USD',
                'markets_traded' => 'Crypto, Forex',
                'monthly_roi' => 8.10,
                'yearly_roi' => 71.20,
                'max_drawdown' => 7.60,
                'aum' => 640000,
                'consistency_score' => 84,
                'volatility_score' => 39,
                'confidence_score' => 88,
                'capital_preservation_score' => 85,
                'recommended_investor_profile' => 'Balanced Growth',
                'minimum_allocation' => 300.00,
                'maximum_allocation' => 12000.00,
                'max_allocation_percent' => 28.00,
                'management_fee_percent' => 1.00,
                'performance_fee_percent' => 10.00,
                'is_featured' => true,
            ],
            [
                'name' => 'Mike Rodriguez',
                'photo' => 'traders/mike-rodriguez.jpg',
                'rating' => 4,
                'followers' => 654,
                'equity' => 79.1,
                'total_profit' => 67800.00,
                'status' => 'active',
                'description' => 'Day trader focusing on high volatility pairs. Great for short-term gains.',
                'bio' => 'Intraday breakout specialist with fast execution and tighter holding windows.',
                'win_rate' => 79,
                'total_trades' => 1567,
                'price' => 250.00,
                'tag' => 'FAST',
                'type' => 'main',
                'verification_status' => 'verified',
                'strategy_type' => 'Breakout Intraday',
                'risk_level' => 'high',
                'trading_style' => 'Intraday',
                'preferred_instruments' => 'GBP/JPY, NAS100, XAU/USD',
                'markets_traded' => 'Forex, Indices, Metals',
                'monthly_roi' => 11.80,
                'yearly_roi' => 96.30,
                'max_drawdown' => 14.70,
                'aum' => 520000,
                'consistency_score' => 71,
                'volatility_score' => 68,
                'confidence_score' => 83,
                'capital_preservation_score' => 63,
                'recommended_investor_profile' => 'Growth Seeker',
                'minimum_allocation' => 250.00,
                'maximum_allocation' => 10000.00,
                'max_allocation_percent' => 22.00,
                'management_fee_percent' => 1.40,
                'performance_fee_percent' => 14.00,
            ],
            [
                'name' => 'Emma Williams',
                'photo' => 'traders/emma-williams.jpg',
                'rating' => 5,
                'followers' => 1100,
                'equity' => 85.7,
                'total_profit' => 156700.00,
                'status' => 'active',
                'description' => 'Long-term strategy expert. Perfect for steady, sustainable growth.',
                'bio' => 'Portfolio-style trend follower focused on compounding and multi-month alpha capture.',
                'win_rate' => 85,
                'total_trades' => 2100,
                'price' => 400.00,
                'tag' => 'STABLE',
                'type' => 'main',
                'verification_status' => 'verified',
                'strategy_type' => 'Trend Following',
                'risk_level' => 'low',
                'trading_style' => 'Positional',
                'preferred_instruments' => 'XAU/USD, US30, EUR/USD',
                'markets_traded' => 'Metals, Indices, Forex',
                'monthly_roi' => 7.20,
                'yearly_roi' => 62.10,
                'max_drawdown' => 5.80,
                'aum' => 1180000,
                'consistency_score' => 91,
                'volatility_score' => 24,
                'confidence_score' => 93,
                'capital_preservation_score' => 92,
                'recommended_investor_profile' => 'Capital Preservation',
                'minimum_allocation' => 400.00,
                'maximum_allocation' => 20000.00,
                'max_allocation_percent' => 35.00,
                'management_fee_percent' => 0.90,
                'performance_fee_percent' => 9.50,
                'is_featured' => true,
            ],
            [
                'name' => 'David Kim',
                'photo' => 'traders/david-kim.jpg',
                'rating' => 4,
                'followers' => 567,
                'equity' => 76.8,
                'total_profit' => 45600.00,
                'status' => 'active',
                'description' => 'Scalping specialist with quick entry and exit strategies.',
                'bio' => 'Latency-aware scalper with strict drawdown discipline and short-duration market exposure.',
                'win_rate' => 76,
                'total_trades' => 1234,
                'price' => 200.00,
                'tag' => 'SCALP',
                'type' => 'main',
                'verification_status' => 'pending',
                'strategy_type' => 'Scalping',
                'risk_level' => 'high',
                'trading_style' => 'Scalp',
                'preferred_instruments' => 'EUR/USD, USD/JPY, BTC/USD',
                'markets_traded' => 'Forex, Crypto',
                'monthly_roi' => 10.30,
                'yearly_roi' => 83.40,
                'max_drawdown' => 16.20,
                'aum' => 390000,
                'consistency_score' => 68,
                'volatility_score' => 72,
                'confidence_score' => 79,
                'capital_preservation_score' => 58,
                'recommended_investor_profile' => 'Growth Seeker',
                'minimum_allocation' => 200.00,
                'maximum_allocation' => 8000.00,
                'max_allocation_percent' => 20.00,
                'management_fee_percent' => 1.50,
                'performance_fee_percent' => 15.00,
            ],
            [
                'name' => 'Lisa Thompson',
                'photo' => 'traders/lisa-thompson.jpg',
                'rating' => 5,
                'followers' => 934,
                'equity' => 88.2,
                'total_profit' => 112300.00,
                'status' => 'active',
                'description' => 'Gold and commodities trading expert with excellent risk management.',
                'bio' => 'Commodities specialist blending macro catalysts with disciplined trend continuation entries.',
                'win_rate' => 88,
                'total_trades' => 1876,
                'price' => 350.00,
                'tag' => 'GOLD',
                'type' => 'main',
                'verification_status' => 'verified',
                'strategy_type' => 'Commodities Macro',
                'risk_level' => 'medium',
                'trading_style' => 'Swing',
                'preferred_instruments' => 'XAU/USD, XAG/USD, WTI',
                'markets_traded' => 'Metals, Commodities',
                'monthly_roi' => 8.90,
                'yearly_roi' => 73.80,
                'max_drawdown' => 6.90,
                'aum' => 720000,
                'consistency_score' => 88,
                'volatility_score' => 31,
                'confidence_score' => 90,
                'capital_preservation_score' => 89,
                'recommended_investor_profile' => 'Balanced Growth',
                'minimum_allocation' => 350.00,
                'maximum_allocation' => 14000.00,
                'max_allocation_percent' => 30.00,
                'management_fee_percent' => 1.10,
                'performance_fee_percent' => 11.00,
                'is_featured' => true,
            ]
        ];

        foreach ($traders as $trader) {
            Trader::query()->updateOrCreate(
                ['name' => $trader['name']],
                $trader
            );
        }
    }
}
